apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    command:
    - "sh"
    - "-c"
    args:
    - "echo hello; sleep 3600"
  - image: busybox
    name: busybox2
    resources: {}
    command:
    - "sh"
    - "-c"
    args:
    - "echo hello; sleep 3600"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
