apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  initContainers:
  - image: busybox
    name: busybox
    command:
    - "sh"
    - "-c"
    args:
    - "wget -O /work-dir/index.html http://neverssl.com/online"
    volumeMounts:
    - mountPath: /work-dir
      name: empty-volume
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: empty-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: empty-volume
    emptyDir: {}
status: {}
