apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: consumer
  name: consumer
  namespace: secret-ops
spec:
  containers:
  - image: nginx
    name: consumer
    resources: {}
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: /var/app
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
