apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: limitrange
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: "250Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
