apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: service-account-user
  name: service-account-user
spec:
  containers:
  - image: nginx
    name: service-account-user
    resources: {}
  serviceAccountName: myuser
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
