apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    resources: {}
    command: 
    - env
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
